name: CI

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: read toolchain
        id: toolchain
        run: |
          CHANNEL=$(yq -oy '.toolchain.channel' rust-toolchain.toml)
          echo "TOOLCHAIN=$CHANNEL" >> "$GITHUB_OUTPUT"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.toolchain.outputs.TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
